stages:
  - pages

pages:
  extends: .docker
  stage: pages
  variables:
    PAGES_BUILD_DIR: "public"
    GITLAB_DOCKER_BUILD: ${CI_REGISTRY}/ci-utilities/ci-commands/gitlab-docker-build
    BUILD: ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ci:iid-${CI_PIPELINE_IID}
  script:
    - dind-run "${GITLAB_DOCKER_BUILD}" --cache-from master build --file gitlab/Dockerfile .
    - mkdir -p "${PAGES_BUILD_DIR}"
    - dind-run "${BUILD}" Rscript -e 'rmarkdown::render("Main text/WHO guidance on use of administrative data.Rmd")'
    - cp "WHO-guidance-on-use-of-administrative-data.html" "${PAGES_BUILD_DIR}"/index.html
  artifacts:
    paths:
      - public
  environment:
    name: "guidance.interventionevaluatr.com"
    url: "http://guidance.interventionevaluatr.com"
  only:
    - master
    - gitlab

.docker:
  tags:
    - docker
  image: ${CI_REGISTRY}/ci-utilities/ci-commands/dind-ci
  services:
    - docker:19.03.1-dind