stages:
  - pages

pages:
  extends: .docker
  stage: pages
  variables:
    PAGES_BUILD_DIR: "public"
    GITLAB_DOCKER_BUILD: ${CI_REGISTRY}/ci-utilities/ci-commands/gitlab-docker-build
    BUILD: ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ci:iid-${CI_PIPELINE_IID}
  script:
    - dind-run "${GITLAB_DOCKER_BUILD}" --cache-from master build --file gitlab/Dockerfile .
    - mkdir -p "${PAGES_BUILD_DIR}"
    - find . -name '*.Rmd' -and \! -path '*/rsconnect/*' -exec dind-run "${BUILD}" Rscript -e 'rmarkdown::render(commandArgs(TRUE)[1], output_dir=commandArgs(TRUE)[2])' {} "${PAGES_BUILD_DIR}" \;
    - find "${PAGES_BUILD_DIR}" -name "WHO*guidance*.html" -exec mv {} "${PAGES_BUILD_DIR}"/index.html \; -quit
  artifacts:
    paths:
      - public
  environment:
    name: "guidance.interventionevaluatr.com"
    url: "http://guidance.interventionevaluatr.com"
  only:
    - master
    - gitlab

.docker:
  tags:
    - docker
  image: ${CI_REGISTRY}/ci-utilities/ci-commands/dind-ci
  services:
    - docker:19.03.1-dind